CREATE DATABASE LAST3FIANL;
USE LAST3FIANL;
/* select top example
CREATE TABLE PERSON(PERSONID INT NOT NULL, 
PERSONNAME VARCHAR(255),
CITY VARCHAR(255),
COUNTRY VARCHAR(255),
PRIMARY KEY(PERSONID));

CREATE TABLE STUDENT(STUDENTID INT IDENTITY(1,1) PRIMARY KEY, STUDENTNAME VARCHAR(255), CITY VARCHAR(255), COUNTRY VARCHAR(255));
INSERT INTO STUDENT(STUDENTNAME, CITY, COUNTRY) VALUES('RAM','KATHMANDU','NEPAL');
INSERT INTO STUDENT VALUES('HARESH','HARIWAN','NEPAL');
SELECT TOP 3 * FROM STUDENT;
*/

SELECT * FROM STUDENT;


/* union operation example
CREATE TABLE ORDERDETAIL(ORDERDETAILID INT NOT NULL IDENTITY(1,1), ORDERNUMBER BIGINT, SUPPLIERNAME VARCHAR(255));
INSERT INTO ORDERDETAIL VALUES(5007,'DHURBA');
SELECT * FROM ORDERDETAIL
SELECT * FROM STUDENT;
SELECT SUPPLIERNAME FROM ORDERDETAIL
UNION
SELECT COUNTRY FROM STUDENT;
*/

/* select any all operator example
CREATE TABLE CUSTOMER(CUSTOMERID INT NOT NULL IDENTITY(1,1), CUSTOMERNAME VARCHAR(255), VILLAGE VARCHAR(255), DISTRICT VARCHAR(255), POSTALCODE BIGINT);
INSERT INTO CUSTOMER VALUES('RAMESH','SANTPUR','RAUTAHAT',545455);

CREATE TABLE PRODUCT(PRODUCTID INT NOT NULL IDENTITY(1,1), PRODUCTNAME VARCHAR(255), SUPPLIERNAME VARCHAR(255), CUSTOMERID INT);
INSERT INTO PRODUCT VALUES('SHAMPOO','CG GROUP',1);
INSERT INTO PRODUCT VALUES('SHOUP','DHURBA',2);
INSERT INTO PRODUCT VALUES('JEANS','MULTI-TECH',3);
INSERT INTO PRODUCT VALUES('T-SHIRT','BUDDHA SUPPLIER',4);
INSERT INTO PRODUCT VALUES('SCOUT','DIPESH DEVELOP',5);
INSERT INTO PRODUCT VALUES('CYLIDER','UGRATARA',6);
INSERT INTO PRODUCT VALUES('FAN','SANKATA',7);
INSERT INTO PRODUCT VALUES('BIKE','HIKVISION',8);
INSERT INTO PRODUCT VALUES('TABLE','MERCANTILE',9);
INSERT INTO PRODUCT VALUES('CHAIN','TALLY',10);

SELECT * FROM PRODUCT;
SELECT * FROM CUSTOMER;

SELECT PRODUCTNAME FROM PRODUCT WHERE PRODUCTID=ANY(SELECT CUSTOMERID FROM CUSTOMER WHERE POSTALCODE=16122);
*/


/* where exists operator example
SELECT CUSTOMERNAME FROM CUSTOMER
WHERE EXISTS
(SELECT PRODUCTNAME FROM PRODUCT WHERE CUSTOMER.CUSTOMERID=PRODUCT.CUSTOMERID);
*/

/* sql backup example
SELECT * INTO BACKUP2030 FROM PRODUCT;
SELECT * FROM BACKUP2030;
SELECT PRODUCTNAME, SUPPLIERNAME INTO PRODUCTBACKUP FROM PRODUCT;
SELECT * FROM PRODUCTBACKUP;
*/


/* backup using join clause example
SELECT PRODUCT.PRODUCTNAME, PRODUCT.SUPPLIERNAME, CUSTOMER.CUSTOMERNAME, CUSTOMER.DISTRICT INTO PRODUCTBACKUP2010 FROM CUSTOMER INNER JOIN PRODUCT ON
CUSTOMER.CUSTOMERID=PRODUCT.CUSTOMERID;
SELECT * FROM PRODUCTBACKUP2010;

SELECT CUSTOMER.CUSTOMERNAME, PRODUCT.PRODUCTNAME, PRODUCT.SUPPLIERNAME, CUSTOMER.DISTRICT INTO BACKUP2090 FROM CUSTOMER LEFT JOIN PRODUCT ON 
CUSTOMER.CUSTOMERID=PRODUCT.CUSTOMERID;
SELECT * FROM BACKUP2090;
*/
