CREATE DATABASE LAST2FINAL;
USE LAST2FINAL;
CREATE TABLE STUDENT(STUDENTID INT NOT NULL, STUDENTNAME VARCHAR(255), FACULTY VARCHAR(255), CITY VARCHAR(255), COUNTRY VARCHAR(255));
INSERT INTO STUDENT VALUES(1,'STUDENT1','FACULTY1','CITY1','COUNTRY1',18000);
INSERT INTO STUDENT VALUES(2,'STUDENT2','FACULTY2','CITY2','COUNTRY2',70000);
INSERT INTO STUDENT VALUES(3,'STUDENT3','FACULTY3','CITY3','COUNTRY3',1200000);
INSERT INTO STUDENT VALUES(4,'STUDENT4','FACULTY4','CITY4','COUNTRY4',80000);
INSERT INTO STUDENT VALUES(5,'STUDENT5','FACULTY5','CITY5','COUNTRY5',85000);
INSERT INTO STUDENT VALUES(6,'STUDENT6','FACULTY6','CITY6','COUNTRY6',40000);
INSERT INTO STUDENT VALUES(7,'STUDENT7','FACULTY7','CITY7','COUNTRY7',35000);
INSERT INTO STUDENT VALUES(8,'STUDENT8','FACULTY8','CITY8','COUNTRY8',45000);
INSERT INTO STUDENT VALUES(9,'STUDENT9','FACULTY9','CITY9','COUNTRY9',50000);
INSERT INTO STUDENT VALUES(10,'STUDENT9','FACULTY9','CITY9','COUNTRY9',90000);
ALTER TABLE STUDENT ADD AGE INT;


ALTER TABLE STUDENT ADD SALARY BIGINT;


SELECT * FROM STUDENT WHERE FACULTY='FACULTY1' OR COUNTRY='COUNTRY9';
SELECT * FROM STUDENT ORDER BY STUDENTID ASC;
SELECT DISTINCT(STUDENTNAME) FROM STUDENT;
DELETE FROM STUDENT WHERE STUDENTID=10;
SELECT AVG(SALARY) FROM STUDENT;
SELECT COUNT(STUDENTID) FROM STUDENT;
SELECT LOWER(STUDENTNAME) FROM STUDENT;
SELECT UPPER(STUDENTNAME) FROM STUDENT;
SELECT MAX(SALARY) FROM STUDENT;
SELECT MIN(SALARY) FROM STUDENT;
SELECT SUM(SALARY) FROM STUDENT;
SELECT SUBSTRING(STUDENTNAME,1,4) FROM STUDENT WHERE STUDENTID=2;
SELECT REPLACE(STUDENTNAME,'STUDENT1','SHYAM') FROM STUDENT;
SELECT STUDENTNAME, SUM(SALARY) FROM STUDENT GROUP BY STUDENTNAME;
SELECT STUDENTNAME, SUM(SALARY) FROM STUDENT GROUP BY STUDENTNAME HAVING SUM(SALARY)>50000;
ALTER TABLE STUDENT ADD POSTALCODE BIGINT;
ALTER TABLE STUDENT DROP COLUMN POSTALCODE;
ALTER TABLE STUDENT 
ALTER COLUMN SALARY INT;
ALTER TABLE STUDENT
RENAME COLUMN SALARY TO ANNUALSALARY;
SELECT STUDENTNAME AS FULLNAME FROM STUDENT;

SELECT STUDENTNAME FROM STUDENT WHERE SALARY BETWEEN 30000 AND 50000;
SELECT * FROM STUDENT WHERE STUDENTNAME IN ('STUDENT1','STUDENT9');
SELECT * FROM STUDENT WHERE CITY LIKE '%2';
SELECT * FROM STUDENT WHERE STUDENTNAME LIKE '%T%';
SELECT * FROM STUDENT WHERE FACULTY LIKE 'F%9';
TRUNCATE TABLE STUDENT;
UPDATE STUDENT SET AGE=50 WHERE STUDENTID=10;
SELECT * FROM STUDENT;



