CREATE DATABASE PROCEDUREDB;
CREATE TABLE STUDENT(STUDENTID INT NOT NULL UNIQUE, STUDENTNAME VARCHAR(255), FACULTY VARCHAR(255), CITY VARCHAR(255), COUNTRY VARCHAR(255));
INSERT INTO STUDENT VALUES(1,'NAME1','FACULTY1','CITY1','COUNTRY1');
INSERT INTO STUDENT VALUES(2,'NAME2','FACULTY2','CITY2','COUNTRY2');
INSERT INTO STUDENT VALUES(3,'NAME3','FACULTY3','CITY3','COUNTRY3');
INSERT INTO STUDENT VALUES(4,'NAME4','FACULTY4','CITY4','COUNTRY4');
INSERT INTO STUDENT VALUES(5,'NAME5','FACULTY5','CITY5','COUNTRY5');
INSERT INTO STUDENT VALUES(6,'NAME6','FACULTY6','CITY6','COUNTRY6');
INSERT INTO STUDENT VALUES(7,'NAME7','FACULTY7','CITY7','COUNTRY7');
INSERT INTO STUDENT VALUES(8,'NAME8','FACULTY8','CITY8','COUNTRY8');
INSERT INTO STUDENT VALUES(9,'NAME9','FACULTY9','CITY9','COUNTRY9');
INSERT INTO STUDENT VALUES(10,'NAME10','FACULTY10','CITY10','COUNTRY10');
SELECT * FROM STUDENT;

CREATE PROCEDURE SELECTALLSTUDENT 
AS
SELECT * FROM STUDENT
GO:
EXEC SELECTALLSTUDENT;

CREATE PROCEDURE ALLSTUDENTDB @FACULTY NVARCHAR(255)
AS
SELECT * FROM STUDENT WHERE FACULTY=@FACULTY
GO:
EXEC ALLSTUDENTDB @FACULTY='FACULTY2';

CREATE PROCEDURE TOTALSTUDENT @FACULTY NVARCHAR(255), @CITY NVARCHAR(255), @COUNTRY NVARCHAR(255)
AS
SELECT * FROM STUDENT WHERE FACULTY=@FACULTY AND CITY=@CITY AND COUNTRY=@COUNTRY
GO:
EXEC TOTALSTUDENT @FACULTY='FACULTY1', @CITY='CITY1', @COUNTRY='COUNTRY1';
